# Generated by Django 4.2.7 on 2023-12-02 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileMixin",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "userprofilemixin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="users.userprofilemixin",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("blog_url", models.URLField(blank=True, max_length=255, null=True)),
                ("exp_level", models.IntegerField()),
                ("github_url", models.URLField(blank=True, max_length=255, null=True)),
                ("job", models.CharField(max_length=255)),
                ("linkedin_url", models.URLField(blank=True, max_length=255, null=True)),
                ("rank", models.IntegerField(verbose_name="User rank accross the platform")),
                ("twitter_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("users.userprofilemixin",),
        ),
    ]
