# Generated by Django 4.2.7 on 2023-12-02 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["domain"], "verbose_name": "site", "verbose_name_plural": "sites"},
        ),
    ]
